name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pring greeting
        run: echo "Hi Andy"
      - name: Pring bye
        run: echo "Bye...................."

  #second-job:
  #  needs first-job
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check uptime and histname
  #      run:  hostname && uptime
      
