name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hi Andy"
      - name: Print bye
        run: echo "Bye...................."

  second-job:
    needs: [first-job]
    runs-on: ubuntu-latest
    steps:
      - name: Check uptime and histname
        run:  hostname && uptime
      
